# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jetscale < Formula
  desc "JetScale CLI — cloud cost optimization from the terminal"
  homepage "https://jetscale.ai"
  version "0.2.5"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jetscale-ai/cli/releases/download/v0.2.5/jetscale_0.2.5_darwin_amd64.tar.gz"
      sha256 "94b421194f5ccda8d43ca63ad698164577532e0bf311f22ec3b261da2b6069c9"

      define_method(:install) do
        bin.install "jetscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jetscale-ai/cli/releases/download/v0.2.5/jetscale_0.2.5_darwin_arm64.tar.gz"
      sha256 "2661b584fba76e40212659c8ef898e1ba8afb40e2f16562f708385b0b13e1a85"

      define_method(:install) do
        bin.install "jetscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jetscale-ai/cli/releases/download/v0.2.5/jetscale_0.2.5_linux_amd64.tar.gz"
      sha256 "a09040699c66401bade87c4c96ac5aace0766bc8d5683c9803cb080239cc00e8"
      define_method(:install) do
        bin.install "jetscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jetscale-ai/cli/releases/download/v0.2.5/jetscale_0.2.5_linux_arm64.tar.gz"
      sha256 "ce464cace0c193d70ebd3419bd2fea723c8dcdf973b66422ee0feb9a6a595ed4"
      define_method(:install) do
        bin.install "jetscale"
      end
    end
  end

  test do
    system "#{bin}/jetscale", "version"
  end
end
